version: '3.8'

services:
  backend:
    image: ujjjx/my-backend-app:latest
    build: ./backend
    ports:
      - "5000:5000"
    environment:
      - FLASK_ENV=development
    networks:
      - app-network

  frontend:
    image: ujjjx/my-frontend-app:latest
    build: ./frontend
    ports:
      - "80:80"
    depends_on:
      - backend
    networks:
      - app-network

networks:
  app-network:
    driver: bridge